site_name: Docker
pages:
- "Home": 'index.md'
- "Introduction": 'intro.md'
- "Dev":
  - "Docker Image": 'dev.md'
  - "Dockerfile": 'dockerfile.md'
  - "Docker Compose": 'compose.md'
- "Swarm": 'swarm.md'
- "UCP": 'ucp.md'
- "Labs": 'labs.md'
- "GUI":
  - "Chrome": "gui_chrome.md"
markdown_extensions:
    - footnotes
